version: '3.7'
services: 
  web:
    image: 'nginx'
    container_name: 'startup_web'
    networks: 
      - dev_env_server
    ports: 
      - '0.0.0.0:80:80'
    volumes:
      - './nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/logs:/var/log/nginx'
      - '../:/var/www/html'
    restart: always
    depends_on:
      - php
  php:
    build: './php/build'
    image: 'startup-php'
    container_name: 'startup_php'
    networks: 
      - dev_env_server
    restart: always
    volumes:
      - '../:/var/www/html'
networks:
  dev_env_server:
    driver: bridge