version: '2'
services: 
  web:
    image: 'nginx:alpine'
    container_name: 'startup_web'
    networks: 
      - startup-networks
    ports: 
      - '0.0.0.0:80:80'
    volumes:
      - './nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/logs:/var/log/nginx'
      - '../:/var/www/html'
    restart: always
    depends_on:
      - php
      - database
  php:
    build: './php/build'
    image: 'startup-php'
    container_name: 'startup_php'
    networks: 
      - startup-networks
    restart: always
    volumes:
      - '../:/var/www/html'
  database:
    image: 'mysql:5.7'
    container_name: 'startup_database'
    networks: 
      - startup-networks
    ports:
      - '0.0.0.0:3306:3306'
    volumes:
      - './mysql/datadir:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1qazse4rfvgy7
networks:
  startup-networks:
    driver: bridge